//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Database_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverCar
    {
        public int id { get; set; }
        public System.DateTime purchaseDate { get; set; }
        public int driverId { get; set; }
        public int carId { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Driver Driver { get; set; }
    }
}
